quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRESQL_USER:parasol}
quarkus.datasource.password=${POSTGRESQL_PASSWORD:parasol}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL_HOST:parasol-db}:5432/${POSTGRESQL_DATABASE:parasol}
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
